function drawFixation(self)
% Draw two lines that are the fixation cross in the middle of
% the screen
Screen('DrawLines', self.window, ...
    self.fixationCoords, self.fixationCrossLineWidth, ...
    self.white, [self.windowXCentre, self.windowYCentre]);

% Instead of a crosshair this plots a dot for fixation
% Screen('DrawDots', self.window, ...
%     [self.windowXCentre; self.windowYCentre], 5, ...
%   self.white, [], 2);
end